/*Proyecto Final Base de Datos I*/
/*Creación de Roles*/
CREATE ROLE Administrator;
CREATE ROLE Reader;
/*Asignar Permismos a Roles*/
GRANT CREATE USER, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,CREATE SYNONYM,
ALTER TABLE,ALTER VIEW, ALTER PROCEDURE,ALTER SYNONYM,
DROP TABLE, DROP VIEW, DROP PROCEDURE,DROP SYNONYM,INSERT, UPDATE, DELETE  TO Administrator;
GRANT SELECT TO Reader;
/*Creacion de Usuarios*/
CREATE USER INVITADO IDENTIFIED BY umgDB2018**;
CREATE USER INGENIEROL3 IDENTIFIED BY 1NG3N13R0DB2018**;
/*Asignar Roles A Usuarios */
GRANT Administrator TO INGENIEROL3
GRANT INVITADO TO Reader;


/* Crear tablas, constraints, index, foreign */
CREATE TABLE departamento (
    id_dep       INTEGER NOT NULL,
    nombre_dep   VARCHAR2(25) NOT NULL
);

ALTER TABLE departamento ADD CONSTRAINT departamento_pk PRIMARY KEY ( id_dep );

CREATE TABLE sede (
    sede_id       NUMBER NOT NULL,
    nombre_sede   VARCHAR2(50) NOT NULL
);

ALTER TABLE sede ADD CONSTRAINT sede_pk PRIMARY KEY ( sede_id );

CREATE SEQUENCE ID_DEP
MINVALUE 1

NOMAXVALUE
START WITH 1
NOCYCLE
CACHE  20
NOORDER;
