/*Proyecto Final Base de Datos I*/
/*Creación de Roles*/
CREATE ROLE Administrator;
CREATE ROLE Reader;
/*Asignar Permismos a Roles*/
GRANT CREATE USER, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,CREATE SYNONYM,
ALTER TABLE,ALTER VIEW, ALTER PROCEDURE,ALTER SYNONYM,
DROP TABLE, DROP VIEW, DROP PROCEDURE,DROP SYNONYM,INSERT, UPDATE, DELETE  TO Administrator;
GRANT SELECT TO Reader;
/*Creacion de Usuarios*/
CREATE USER INVITADO IDENTIFIED BY umgDB2018**;
CREATE USER INGENIEROL3 IDENTIFIED BY 1NG3N13R0DB2018**;
/*Asignar Roles A Usuarios */
GRANT Administrator TO INGENIEROL3
GRANT INVITADO TO Reader;


